### ISSUE TITLE
Auto sha256

### ISSUE THREAD

**Issue by MHM5000** [mozilla/django-csp#127]
Can this be done?

**Comment by darakian** [comment]
Can you elaborate on what you mean by auto sha256? Do you mean auto hashing all js/css?

**Comment by MHM5000** [comment]
let's assume something ugly:

```
{% block headjs %}
console.log( {{ some_data }} );
{% endblock headjs%}
```

And of course, we are extending `base.html` where we have a `script` tag with `django-csp` loaded.

We could use a nonce, obviously. But what would the implementations of sha-256 look like? Is it possible? Considering all the whitespaces and other quirky parts of it. Is it worth it?

**Comment by darakian** [comment]
Intuitively I think it could be done for all locally hosted js, but if you're including js from a remote server then django would need to download that file and hash it before serving the page. This could be a DOS attack vector in the worst case or a large performance hit in a better case.

**Comment by MHM5000** [comment]
Obviously we need a caching system. Both for local and remote js/css.

And of course, we need to make sure `django-csp` is the last process of it's kind. There may be some sort of postcss/pre-processing activated on the same block of code.

**Comment by darakian** [comment]
I'm not sure it make sense to add a caching system to django csp.

**Comment by g-k** [comment]
I'm going to close this, since we're trying to keep django-csp narrowly scoped to just serving CSP headers. Also, per https://github.com/mozilla/django-csp/issues/127#issuecomment-555655483 it potentially exposes users to DoS. SSRF and making everything work with CDNs and various network perspectives are also concerns.

Making it easier to construct and adopt a good CSP is generally desirable, and I have some coworkers with projects in that area you might want to check out:

* April wrote a Firefox extension https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/
* ZAP https://www.zaproxy.org/ has a CSP extension. I believe it has a mode to create a CSP for a session of proxied traffic 
* browser dev tools consoles will log suggested hashes for a file

However, tighter django integration definitely be helpful especially in development, so I'd encourage you to write a sibling library to do that.
