### ISSUE TITLE
Python 3.6 "DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7"

### ISSUE THREAD

**Issue by g-k** [mozilla/django-csp#136]
```
=============================== warnings summary ===============================

csp/tests/test_jinja_extension.py::TestJinjaExtension::()::test_async_attribute_with_falsey

  <template>:19: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7

```

from https://travis-ci.org/mozilla/django-csp/jobs/620263360

Doesn't actually result in errors on 3.7 and 3.8 w/ django master.

**Comment by DylanYoung** [comment]
What's the desired action here? Silence the deprecation warning?

**Comment by g-k** [comment]
Just documenting it in this issue. I don't think we should suppress the warning, but if we can refactor to avoid the warning that'd be nice.

**Comment by DylanYoung** [comment]
Oki dokie, just wanted to clarify because you said there was no impact aside from the warning.

**Comment by DylanYoung** [comment]
After exploring, I think the warning should just be silenced or left alone.  We aren't shadowing any builtins here since everything is encapsulated in kwargs.  If we do choose to remove it, I'd recommend also changing the `id` parameter similarly as it's another builtin. 

I *believe* I've successfully removed the deprecation warning, but I'm not 100% as I'm running python 3.7.  if I haven't, then it's internal to jinja and I don't think there is anything to be done about it aside from breaking back-compat.  

What we could do is introduce a second syntax: `async_attr` and `id_attr`  then use these in the tests (and have one using the original versions that tests for the warning being raised).

**Comment by DylanYoung** [comment]
Can you confirm if that commit removes the warning?

**Comment by g-k** [comment]
Thanks for digging into this. Still seeing it for:

3.6-2.2.x https://app.circleci.com/pipelines/github/mozilla/django-csp/36/workflows/758209e6-b7e6-4898-bead-cdbd83fc38d7/jobs/808
3.6-3.2.x https://app.circleci.com/pipelines/github/mozilla/django-csp/36/workflows/758209e6-b7e6-4898-bead-cdbd83fc38d7/jobs/817

but not for other python versions, I think it's best left alone like you suggested in https://github.com/mozilla/django-csp/issues/136#issuecomment-597180808
