### ISSUE TITLE
Nonce Value Not 128 bits

### ISSUE THREAD

**Issue by 9mido** [mozilla/django-csp#148]
https://github.com/mozilla/django-csp/blob/master/csp/middleware.py#L37

https://www.w3.org/TR/CSP3/

According to section 7.1 a nonce should be 128 bits. HTML5 validators gives a warning "Content-Security-Policy HTTP header: Bad content security policy: CSP specification recommends nonce-value to be at least 128 bits long (before encoding)."

```
CSP_INCLUDE_NONCE_IN=['script-src']
<script nonce="{{request.csp_nonce}}">
Outputs <script nonce="oLhixKzv6xJ6hOeE">
```

```
import base64
len(base64.b64decode('oLhixKzv6xJ6hOeE'))
12
```

12*8 = 96
That is only 96 bits
It should be 16 bytes base64 encoded

The documentation says it will do nonce-`<b64-value>` but the code doesn't do that.

It does nonce-<get_random_string(length)>

get_random_string() is a django crypto helper. If length isn't specified, it defaults to 12.

If the browser is expecting base64, 16 bytes of base64 will always decode to 12 bytes or 96 bits. Not the 128 bits the browser is expecting.

**Comment by 9mido** [comment]
One workaround is to change 

`def _make_nonce(self, request, length=16): `

to

`def _make_nonce(self, request, length=24):`

but this is not a desirable fix since this is not base64. 

or the function needs to be re-written with 

`b64encode(os.urandom(16))`

It will be multiple of 4 base64 digits if "=" are digits also since the standard expects base64 and it allows up to two "=".

https://www.w3.org/TR/CSP/#grammardef-nonce-source

**Comment by 9mido** [comment]
@EnTeQuAk 

This issue has been resolved. Please check and update the project and submit this newest change to PyPi.

**Comment by wpodgorski** [comment]
@9mido @EnTeQuAk @graingert I do not believe that fix provided in https://github.com/graingert/django-csp/commit/cc1735b87590b281338752021bfa30a8c7a4f74d is the best way to go. Before, `_make_nonce()` used Django's `get_random_string()` method to obtain the actual value of nonce. Apart from CSP's nonce definition regarding Base64 encoding, we have to ensure that nonce value is generated using CSPRNG and utilizes the highest-quality sources provided by the operating system to achieve that. This is not the case in this fix. Notice that previously Django was responsible for underlying random number generator. Depending on version it was done [better](https://github.com/django/django/blob/3.0.7/django/utils/crypto.py#L37) or [worse](https://github.com/django/django/blob/2.2.13/django/utils/crypto.py#L48). In the newest version there is [no length provided by default](https://github.com/django/django/blob/master/django/utils/crypto.py#L54) and method uses `secrets` module for generating value of nonce, which provides the best possible random source provided by OS. We, on the other hand, are falling back to `os.urandom()` for generating random bytes. I believe that proper implementation would use one of the following approaches (in order of preference):

1. Make use of `secrets` module in custom implementation, this breaks the backwards compatibility but should be ok since the newest version is compatibile with Python 3.6, 3.7, 3.8, pypy3:
```python
    import secrets

    def _make_nonce(self, request):
        # Ensure that any subsequent calls to request.csp_nonce return the
        # same value
        if not getattr(request, '_csp_nonce', None):
            request._csp_nonce = (
                base64
                .b64encode(secrets.token_bytes(16))
                .decode("ascii")
            )
        return request._csp_nonce
```
or even better
```python
    import secrets

    def _make_nonce(self, request):
        # Ensure that any subsequent calls to request.csp_nonce return the
        # same value
        if not getattr(request, '_csp_nonce', None):
            request._csp_nonce = secrets.token_urlsafe(16)
        return request._csp_nonce
```
2. Use Django's `get_random_string()` method but with different parameters:
```python
    import string
    # via https://www.w3.org/TR/CSP3/#grammardef-base64-value
    BASE64_CHARSET = string.ascii_letters + string.ascii_digits + '+/-_='

    def _make_nonce(self, request):
        # Ensure that any subsequent calls to request.csp_nonce return the
        # same value
        if not getattr(request, '_csp_nonce', None):
            request._csp_nonce = get_random_string(length=22, 
                                                   allowed_chars=BASE64_CHARSET)
        return request._csp_nonce
```
3.  Custom implementation depending on used Python version which uses best CSPRNG for given Python version & underlying OS. Backward compatible but harder to implement.

Moreover, I think this is the time where CSP nonce length should be configurable e.g. via `CSP_NONCE_BITS` variable. I am open for discussion, please let me know what you think. Thank you!

**Comment by graingert** [comment]
secrets just uses os.urandom: https://github.com/python/cpython/blob/3.8/Lib/secrets.py#L47

**Comment by graingert** [comment]
token_urlsafe and get_random_string with a base64 alphabet also doesn't work: https://github.com/mozilla/django-csp/pull/152#discussion_r436368994

**Comment by graingert** [comment]
I can't see a use case for a CSP_NONCE_BITS setting it's just a foot gun for someone to set too low. Adding additional knobs and dials to crypto systems has been a major source of complexity and vulnerabilities

If the recommendation in the spec increases a patch can be released with a bigger number

**Comment by 9mido** [comment]
@pmac please upload these newest changes to PyPi.
