### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bobwhitelock** [mozilla/django-csp#184]
There's been over a year's worth of changes since 3.7, would we be able to get a new release? Thanks!

**Comment by mlec1** [comment]
Is there any update about a new release ?

**Comment by pulse-mind** [comment]
Hello,

This project looks nice but looks dead :/. 

Is there someone that can create release ?

**Comment by stevejalim** [comment]
I've recently been given write access and will be making time to do a new
release. I suspect that'll be as early as I can in 2024 I'm afraid

**Comment by pulse-mind** [comment]
Thank you for your answer and thank you for your job on this project !

**Comment by stevejalim** [comment]
OK, starting to get things moving again: https://github.com/mozilla/django-csp/pull/204

**Comment by stevejalim** [comment]
Hello all - i've just spun up https://pypi.org/project/django-csp/3.8rc0/ 

If you can spare a little time to test-drive it in your project(s), that would be very much appreciated. 

Functionally, there's nothing new on top of 3.7; it's just been housekeeping - see https://github.com/mozilla/django-csp/blob/main/CHANGES

cc @tim-schilling @asottile-sentry @robhudson (as people who might also be interested in this RC, but who are not subscribed)

**Comment by stevejalim** [comment]
3.8rc0 seems fine on www.mozilla.org and support.mozilla.org so I think we can ship it as 3.8.

If anyone following this thread has tried it out and has spotted problems, please let us know by Monday 26 Feb - thanks!

**Comment by stevejalim** [comment]
Just released [3.8rc1](https://pypi.org/project/django-csp/3.8rc1/) with a minor packaging change (switch to pyproject.toml). 

No regressions were noted in 3.8rc0, so unless the packaging change causes people pain, we can get this out to formal release v soon. 

(If the release process seems slow, it's because I'm juggling a lot and don't want to rush it, naturally.)

On that note, if you're following this ticket, please can you spare 5 mins to try a quick pip/poetry/uv/whatever install of 3.8rc1 and report back ASAP if there are any rough corners - thanks y'all! 🙇

**Comment by oioki** [comment]
Hey @stevejalim 
We use django-csp in https://github.com/getsentry/sentry/
Just in case, I tried `3.8rc1` on local dev environment, and it worked fine. Excited about the upcoming release. 🙂

**Comment by mlec1** [comment]
I use it also in 3 different projects. No issue on local dev either, it is working fine for the version `3.8rc1`

**Comment by stevejalim** [comment]
Version 3.8 is now on PyPI 🎉 

Thanks to everyone who contributed to it - https://github.com/mozilla/django-csp/releases/tag/3.8

https://pypi.org/project/django-csp/
