### ISSUE TITLE
Unrecognized Content Security Policy directive 'worker-src' in Safari Browser

### ISSUE THREAD

**Issue by sandeepks230** [mozilla/django-csp#187]
I have a django app that is embedded in Shopify. It is working fine in all other browsers except in Safari Browser. In safari there is the above mentioned issue in the log and getting internal server error for all other functionalities of the app.This is a part of my settings.py for the CSP settings:
`CSP_FRAME_ANCESTORS = ("'self'", 'https://*.myshopify.com')

CSP_DEFAULT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://fonts.gstatic.com")

CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")

CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")

CSP_IMG_SRC = ("'self'",
               "https://*.s3.amazonaws.com", "data:", "https://cdn.shopify.com")

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
XS_SHARING_ALLOWED_METHODS = ['POST', 'GET', 'PUT']

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CSRF_TRUSTED_ORIGINS = [config('CSRF_TRUSTED_ORIGINS')]`

Can anyone tell me what's the issue here?

**Comment by some1ataplace** [comment]
It looks like the issue you are experiencing is related to the worker-src Content Security Policy directive, which is not supported in Safari Browser. One solution to this problem is to remove the worker-src directive from your Content Security Policy headers. 

The error message "Unrecognized Content Security Policy directive 'worker-src'" in Safari browser suggests that the 'worker-src' directive is not supported by Safari. You may want to remove it from your CSP settings. Additionally, make sure that the other directives in your CSP settings are compatible with Safari.

**Comment by robhudson** [comment]
The `worker-src` directive should only be included in the policy header if `CSP_WORKER_SRC` is set.
