### ISSUE TITLE
interested in adding typing (mypy) support?

### ISSUE THREAD

**Issue by asottile-sentry** [mozilla/django-csp#198]
this would allow users to typecheck their usage of this middleware -- it seems pretty simple (there's only a few public functions) and could be checked in CI with mypy

for now I'm creating some `.pyi` stubs in sentry which are enough for my use right now -- but it might be nice to share these more broadly via this package

**Comment by stevejalim** [comment]
Hi @asottile-sentry - been a while since you opened this, but I'm dusting off the project.

Your suggestion makes sense, yeah. If you'd be up for sharing the `.pyi`s via the project, that sounds cool. `main` is healthy now and has GH Actions for CI so feel free to PR off that branch if and whenever you fancy it. Cheers!

**Comment by Greyvend** [comment]
Any updates on this? mypy checks are failing with


```
Skipping analyzing "csp.decorators": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

**Comment by asottile-sentry** [comment]
I started adding inline annotations but other things were higher priority -- we use this `.pyi` file with very incomplete types:  https://github.com/getsentry/sentry/tree/9a31bb0dc5073c04e892b7a570d33ca609518321/fixtures/stubs-for-mypy/csp

**Comment by robhudson** [comment]
Type hints were added in #228. Thank you for the suggestion.
