### ISSUE TITLE
Documentation incorrectly shows EXCLUDE_URL_PREFIXES as a list of strings instead of a tuple of strings

### ISSUE THREAD

**Issue by wnicolaas** [mozilla/django-csp#241]
The following example can be found in the documentation:

```
CONTENT_SECURITY_POLICY = {
    "EXCLUDE_URL_PREFIXES": ["/excluded-path/"],
    "DIRECTIVES": {
        "default-src": [SELF, "cdn.example.net"],
        "frame-ancestors": [SELF],
        "form-action": [SELF],
        "report-uri": "/csp-report/",
    },
} 
```
However, when using the CSP middleware this will cause errors in middelware.py:49 & middleware.py:59 as `startswith` in `request.path_info.startswith(prefixes)` expects a string or tuple of strings, otherwise it will throw a TypeError.

Using a tuple instead managed to fix the issue for me.

**Comment by robhudson** [comment]
Thanks for taking the time to report an issue! 🙏 

I believe this might be a case of reading the docs for the "latest" release, which is 4.0b1, but running against the last stable release, which is 3.8.

The 4.0b1 release is a backwards-incompatible change documented here:
https://django-csp.readthedocs.io/en/latest/configuration.html#migrating-from-django-csp-3-8

The above syntax, including the list of strings for `EXCLUDE_URL_PREFIXES` should work against 4.0b1 since the middleware now wraps this using `tuple(...)`.

If this is incorrect, please re-open and I'll investigate further.

**Comment by wnicolaas** [comment]
Hi @robhudson, I'm not entirely sure I understand this correctly, but I believe the "latest" version on the docs corresponds to 4.0b1, correct?

In that case the issue still stands, as I encountered this while using 4.0b1. Looking at the changelog for 4.0b1 I cannot see the middleware change you mentioned either, unless I am missing something. As for reopening the issue, I'm afraid I don't have the required permissions.

If I can be of any further assistance, let me know.

**Comment by robhudson** [comment]
Ah, the change in 2bb3e6d6 was committed after 4.0b1 was released. So we're probably due for a 4.0b2. I can try to push that out this week which will include the fix I mentioned above.

I'll re-open this until that is released. 

Thanks again!

**Comment by robhudson** [comment]
[4.0b2 released](https://github.com/mozilla/django-csp/releases/tag/4.0b2)
