### ISSUE TITLE
nonce support

### ISSUE THREAD

**Issue by sobolevn** [mozilla/django-csp#48]
There's a lack of support for this feature.
I think that `{% csp_nonce %}` in conjunction with some kind of random string generation in headers might do the trick.

What do you think?

**Comment by jsocol** [comment]
@mozmark and I were talking about this a lot over the summer—...oh apparently summer 2014—and kind of got sidetracked. To sum up a lot of our conversation:

My opinion is that we should do what @sobolevn described: add it to template context and the headers. We could add a template tag that just outputs the nonce, too, but I think that's unnecessary sugar. (We also talked about hash-source support which is more difficult and I think we should do that separately.) Something like:

```jinja
<script nonce="{{ CSP_NONCE }}">
```

gets us there with a very simple template context processor and middleware.

Mark favored something more complex, using a `{% script %}` block. I don't know if he still does. The goal of the block was to prevent people from using any template variables or statements inside a `{% script %}` block without opting in with something like `{% script 'dangerous' %}`. And it papers over the implementation details of nonce-source.

I didn't like that solution because it's a lot more code (and maintenance and surface area) for little security win. You can't stop template authors from writing `<script>` or finding the nonce value on the `request` object (where it would almost certainly need to live) and doing `<script nonce="{{ request._csp_nonce }}">`, even if you say "you should use a `{% script %}` block". I also don't think papering over the implementation details is a good thing, here.

Maybe a `{% script %}` is necessary for hash-source support—but that's a bigger and different problem.

**Comment by sobolevn** [comment]
Thank you for a detailed aswer. For me forcing a developer to use custom `{% script %}` tag seems weird. However, it might be usefull as a separate solution.

I will have some spare time in a week or two, I can help you with `{{ CSP_NONCE }}`.

**Comment by mozmark** [comment]
I'm OK with people doing weird things if it makes them less likely to write security holes (feel free to take my opinion with a pinch of paranoid-security-type salt).

I do still favor the {% script %} block because:
* nonce-source, while useful, can be a dangerous foot gun.
* People do a good job of shooting themselves in the foot  - especially when doing so is easy (see also: XSS).
* Providing a safe-by-default way to use a feature is a good thing (and something I expect from Django as a developer).
* Providing convenient access to a foot gun in a way that makes it clear that the foot gun is dangerous is OK.
* People go digging around for stuff on the request object, they probably realize they're doing a bad thing.
* If people are using Django, they're probably OK with papering over an implementation detail or two.

**Comment by systemsoverload** [comment]
Having not seeing any updates and being in need of the nonce feature, we went ahead and implemented `request.csp_nonce` for use in some newrelic template tags. Given that this feature doesn't impede the `{% script %` or context processor based approach (and may in-fact serve as the basis of it), would you be opposed to me opening a PR with this feature?

**Comment by aventurella** [comment]
I needed this yesterday I did this (2 files):

Add the following to your template context processors:
```
your.app.context_processors.nonce
```

Add the following to middleware AFTER the CSPMiddleware:

```
...
'csp.middleware.CSPMiddleware,
your.app.middleware.CSPNonceMiddleware',
...
```

It works, it's gonna blow up if you use the @csp_update decorator in conjunction, I probably need to merge that if it's there in the middleware.  Anyway if nothing else it's a first draft if someone else needs it.

## Context Processor:

```
from typing import List
import base64
import uuid


class CSPNonceGenerator:

    def __init__(self, request) -> None:
        self.request = request
        self.registry = []  # type: List[str]

    @property
    def nonce(self) -> str:
        data = base64.b64encode(uuid.uuid4().bytes).decode('utf8')
        nonce = "{}".format(data)
        self.registry.append(nonce)
        return nonce


def nonce(request):
    generator = CSPNonceGenerator(request)
    request._ff_csp_nonce_generator = generator
    return {"csp_nonce": generator}
```


## Response Middleware:

```
try:
    from django.utils.deprecation import MiddlewareMixin
except ImportError:
    class MiddlewareMixin(object):
        """
        If this middleware doesn't exist, this is an older version of django
        and we don't need it.
        """
        pass


class CSPNonceMiddleware(MiddlewareMixin):

    def process_response(self, request, response):

        generator = getattr(request, "_ff_csp_nonce_generator", None)

        if generator:
            nonce_collection = generator.registry
            response._csp_update = {
                "default-src": ["'nonce-{}'".format(x) for x in nonce_collection]
            }

        return response
```

**Comment by ananthb** [comment]
I really need the nonce tag to work and I have some time to volunteer. What can I do? @mozmark @jsocol @sobolevn

**Comment by EnTeQuAk** [comment]
@ananthb there is already some work in our current master that got done in https://github.com/mozilla/django-csp/pull/75 and in https://github.com/mozilla/django-csp/pull/77 which you should be able to use. There isn't any documentation about it but it's WIP.

**Comment by ogonkov** [comment]
Latest version with nonce context processor is not published to pip yet?

**Comment by jon-torodash** [comment]
Does any maintainer have an answer to @ogonkov's question? It's on master, but not in tag 3.3, which is the version pip installs by default.

**Comment by g-k** [comment]
It's not published. 3.3 is the most recent one https://pypi.python.org/pypi/django_csp

**Comment by EnTeQuAk** [comment]
Yes, I haven't published this yet since I didn't have the time to give https://github.com/mozilla/django-csp/pull/78 an in-depth review. Happy for help, otherwise I'll try squeezing this in in the next two weeks.

**Comment by ogonkov** [comment]
I have to install it with latest commit and it's seems works for me w/out any visible flaws

**Comment by ogonkov** [comment]
I'm not sure that #78 is blocking master from releasing as separate version. master has nice basic support of `nonce` that "just works".

**Comment by EnTeQuAk** [comment]
fair point, let me glance over what landed recently and push out a new release later today.

**Comment by JirkaV** [comment]
Anything a layman can do to help? I don't have the skills to fully review, but would be really interested in seeing this happening, so offering help with testing or partial review

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/django-csp/pull/75
https://github.com/mozilla/django-csp/pull/77
https://github.com/mozilla/django-csp/pull/92
https://github.com/mozilla/django-csp/pull/78

Added support for this so I'm going to close this issue for now. We're going to see how it works in real-life and I'm looking forward to get some feedback!

**Comment by sobolevn** [comment]
@EnTeQuAk sorry, I am unable to find any docs about this feature: https://django-csp.readthedocs.io/en/latest/search.html?q=nonce&check_keywords=yes&area=default

Is it released?

**Comment by EnTeQuAk** [comment]
the readthedocs build is currently broken, you can look at https://github.com/mozilla/django-csp/blob/master/docs/nonce.rst in the meantime.

**Comment by sobolevn** [comment]
@EnTeQuAk do you have plans on releasing a new version with `nonce` support?

**Comment by EnTeQuAk** [comment]
I just released version 3.5 on pypi, https://twitter.com/entequak/status/1085572155138629635 - sorry for the long wait.

**Comment by FirefighterBlu3** [comment]
Is `csp.context_processors.nonce` supposed to handle (cover) all other installed apps/middleware? I have `django-pwa` which installs a serviceworker.js by means of a script tag inside itself, but the generated output that appears in the browser doesn't include nonce data.

project level `settings.py`
```python
INSTALLED_APPS = [
...
    'pwa',
]

MIDDLEWARE = [
...
    'csp.middleware.CSPMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
...
                'csp.context_processors.nonce',
            ],
        },
    },
]
```

and this snippet comes from `env/lib/python3.7/site-packages/pwa/templates/pwa.html`, using either `{{nonce}}` or `{{request.csp_nonce}}`:
```javascript
<script type="text/javascript" nonce="{{nonce}}">
...
```

The output HTML has `nonce=""`

`env/lib/python3.7/site-packages/pwa/templatetags/pwa.py` appears to register things ok:
```python
import json

from django import template
from django.core.serializers.json import DjangoJSONEncoder
from django.utils.safestring import mark_safe

from .. import app_settings

register = template.Library()


@register.filter(is_safe=True)
def js(obj):
    """ Transform a python object so it can be safely used in javascript/JSON. """
    return mark_safe(json.dumps(obj, cls=DjangoJSONEncoder))


@register.inclusion_tag('pwa.html', takes_context=True)
def progressive_web_app_meta(context):
    # Pass all PWA_* settings into the template
    return {
        setting_name: getattr(app_settings, setting_name)
        for setting_name in dir(app_settings)
        if setting_name.startswith('PWA_')
    }
```

**Comment by FirefighterBlu3** [comment]
disregard my last comment. the django-pwa project filters out everything but PWA_* for template values. reference: https://github.com/silviolleite/django-pwa/issues/21
