### ISSUE TITLE
Versioned docs for the tagged packages versions don't appear to be available on RTD

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/django-csp#63]
For example when we start changing the docs it would be nice if users of the older version can still get the docs for that version. Right now it looks like rtd only has latest and stable.

**Comment by g-k** [comment]
👍 especially if we make breaking changes.

If an RTD admin for the project goes to: https://readthedocs.org/projects/django-csp/versions/

and marks the old inactive versions as active in RTD then it should look like:

<img width="861" alt="screen shot 2016-12-30 at 2 43 51 pm" src="https://cloud.githubusercontent.com/assets/226605/21571566/9abb1710-ce9e-11e6-81dd-5e4e956e34a8.png">

and we should have versions going back to 2.0 available like: http://g-k-django-csp.readthedocs.io/en/v2.0/

Note: 2.0.1 failed to build but everything else was OK: https://readthedocs.org/projects/g-k-django-csp/builds/4844443/


Also, in RTD I had go to Admin > Settings > Advanced Settings and check install project to get the docs building for my branch since https://github.com/mozilla/django-csp/commit/de1e45c3668a1fe37f6c89887d5aabeb9251e5f8#diff-85987f48f1258d9ee486e3191495582dR52 looks for the distribution.  It ended up looking like:

<img width="484" alt="screen shot 2016-12-30 at 2 50 49 pm" src="https://cloud.githubusercontent.com/assets/226605/21571690/a30782a4-ce9f-11e6-98c0-9539eb8eadcc.png">

If we already have those things enabled, I'm not sure what's going on.

**Comment by muffinresearch** [comment]
This is done now.
