### ISSUE TITLE
Pip install not updated

### ISSUE THREAD

**Issue by edgarmiro** [mozilla/django-csp#66]
Installation with Pip has no recent changes. For example, in **from_settings** from file **utils.py** the policies 'base-uri', 'child-src', 'form-action' and 'frame-ancestors' do not exist.

**Comment by EnTeQuAk** [comment]
You mean the package on pypi? We haven't released a new version yet. I'd like to get https://github.com/mozilla/django-csp/issues/50 done first I think since we already have a major release coming up anyway.

You can always use a source-installation if you need the current master, `pip install git+https://github.com/mozilla/django-csp.git`

Because of this I'm going to close this issue but please feel free to re-open if you have any more issues with that.

**Comment by edgarmiro** [comment]
Yes, i mean the package on pypi.
Thanks!
