### ISSUE TITLE
Refused to load script -  data:application/javascript;base64,...

### ISSUE THREAD

**Issue by GinoHereIam** [mozilla/django-csp#73]
Hi!
I've got an issue to load base64 data. Even I put it like this:
```python
CSP_SCRIPT_SRC = (
    "'self'", "'unsafe-inline'", 'disqus.com', '*.disquscdn.com',
    '*.disqus.com', 'data:'
    )
```
What I do may wrong?

Gino

**Comment by muffinresearch** [comment]
Can you provide more details as to why you think this is a bug with django-csp? What is the header output you're seeing for the above config?

It's also worth noting data: URIs are unsafe and can open your web site up to cross-site scripting vulnerabilities if allowed for script-src.

**Comment by GinoHereIam** [comment]
There is a `scheme definition` for CSP to allow data uri, which is `data:` and it works pretty fine with .htaccess but not with this great django plugin.

Here are the policy directives: [https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives)

Therefore I think it is bug.

I know it is unsafe, but how else I get disqus working without let it through?

**Comment by muffinresearch** [comment]
Specifying `data:` is a valid source-list entry but what's unclear is django-csp's role in the issue you're seeing. 

Can you provide the CSP headers output by your django app looking at a given request that's failing - is django-csp outputting `data:` in the script-src directive?

**Comment by muffinresearch** [comment]
> I know it is unsafe, but how else I get disqus working without let it through? 

Are you sure disqus requires data uris? I run disqus on my blog with CSP and I'm not allowing `data:`. The only time I've ever seen something trying to load JS data-uris is when you have ad-blocking turned on and google analytics is blocked. Google appears to try loading analytics via a data-uri in those cases.

**Comment by Bennyoak** [comment]
Hi @GinoHereIam 

I've been working with django-csp for a while, and it's usually good at staying out of the way. It's really passive in that it just spits out the directives you specify in your settings file. django-csp literally just grabs and parses the tuple and doesn't make much of a decision on whether or not a value is valid. If I had to guess, based on the config you posted and what's actually being shown in the screenshot:

A) Not to be too pedantic, but I noticed `data:` isn't listed under `script-src` in the screenshot. Are you saying that you're listing `data:` in your `CSP_SCRIPT_SRC`, but it's not spitting out that particular value?

B) You also mentioned .htaccess - If you have django-csp _and_ .htaccess configuring your CSP, there may be a conflict if they're trying to deliver the same directive...

C) As awesome as CSP is... it's still a nightmare to deal with because every browser has their own way of implementing it. Not to mention that there are still browsers that only support CSP Level 1 (IIRC - `data:` isn't a thing in Level1) and just parts of CSP Level 2. This may be a case where BrowserX doesn't support `data:` but BrowserY is just fine with it. 

Hope this helps provide some debugging leads. Sorry for the long post.

**Comment by GinoHereIam** [comment]
Hi you both,

@muffinresearch that's a pretty good hint that you run disqus without let `data:` through! 
Do you mind to show me how you configured `CSP for disqus`? I was freaking out to change my CSP all time, because I can't test it localhost.

@Bennyoak 
to A) You can see it on my first comment. `data:` is on the last position. But anyway I won't let it through as I don't need it.

to B) forget it please, it was just a comparios that `data:` works fine in .htaccess, for example if I have base64 encoded pictures. That's why I think it should actually work in CSP either.

to C) thanks for this! I didn't know about it! I thought it comes with CSP and not the browser. 

@muffinresearch I would be happy if you could tell me what domains you let through for disqus. There is no brief, right now it's just trial-and-error. :D

Thanks for your both help! I admit it! I'll test it with a bare-bones browser. Adblock and disconnect might change the behavior.

**Comment by muffinresearch** [comment]
I'm going to close this issue since I don't think there's any problem with django-csp. Please re-open if you think you have a problem with the headers django-csp is sending.

For reference I'm using the following for disqus on my personal [blog](https://muffinresearch.co.uk).

```
frame-src 
    https://disqus.com;
img-src 
    https://disqus.com 
    https://referrer.disqus.com/juggler/
    https://a.disquscdn.com;        
script-src
     https://[your-site-name].disqus.com/embed.js 
     https://a.disquscdn.com/embed.js
     https://disqus.com/next/config.js;
style-src 
     'unsafe-inline'  
     https://a.disquscdn.com;
```

Since it's just my personal blog I've not gone that far with making sure it's the most minimal config possible, there's almost certainly room for locking the config down further.

IIRC unsafe-inline was needed for the style-src because disqus uses inline style elements instead of directly changing the style properties of elements directly. But as always, things change, so the best approach is to build up your directives piece by piece and make sure you really do need something before including it.

Another tip is to make sure logging in and out of disqus works, since this makes quite a lot of different requests and creates different frames.

You might also find these tools and sites useful if you haven't already come across them the latter is particularly useful for ensuring you're not allowing hosts that have known CSP bypasses via JSONP endpoints.

* https://observatory.mozilla.org/
* https://csp-evaluator.withgoogle.com/
